#!/bin/bash
#SBATCH -p compute
#SBATCH -J llama31_eval
#SBATCH --gres=gpu:rtxa6000:1

cd /home/nreche/portable_lora/
source .venv/bin/activate
mkdir -p predictions logs

ctg_attributes=("topic" "topic")
seeds=(7097 4613 89723)
models=("llama31" "llama32")

for seed in "${seeds[@]}"; do
    for model in "${models[@]}"; do
        for attribute in "${ctg_attributes[@]}"; do
            output_file="outputs/llama31_to_${model}_${attribute}_seed${seed}.json"
            pred_file="predictions/llama31_to_${model}_${attribute}_seed${seed}.json"
            if [ -f "$output_file" ]; then
                echo "Evaluating $output_file ..."
                python scripts/main_eval.py --config config/evaluate_${attribute}.yaml --seed $seed --output_file "$output_file" --predictions_file "$pred_file"
            fi
        done
    done
done
