#!/bin/bash
#SBATCH -J identity_inf
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=90000

cd /home/nreche/portable_lora/
source .venv/bin/activate

seeds=(7097)

for seed in "${seeds[@]}"
do
    # LLaMa 3.1 8B sur lui-même
    uv run scripts/run_portability.py --step generate --seed $seed \
        --module models/sft_llama3.1_8b_sentiment_seed${seed}/checkpoint-400/ \
        --src_model llama31 --tgt_model llama31 --attribute sentiment \
        --dataset data/pplm_prompts.csv data/sts_benchmark_processed.csv data/sts_benchmark_test_subset.csv \
        --output outputs/identity_llama31_sentiment_seed${seed}.json

    # LLaMa 3.2 3B sur lui-même
    uv run scripts/run_portability.py --step generate --seed $seed \
        --module models/sft_llama3.2_3b_sentiment_seed${seed}/checkpoint-400/ \
        --src_model llama32 --tgt_model llama32 --attribute sentiment \
        --dataset data/pplm_prompts.csv data/sts_benchmark_processed.csv data/sts_benchmark_test_subset.csv \
        --output outputs/identity_llama32_sentiment_seed${seed}.json
done
