#!/bin/bash
#SBATCH -J rl_train
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4

cd /home/nreche/portable_lora/
source .venv/bin/activate

ctg_attributes=("sentiment")
seeds=(7097) # Testing on a single seed first to verify that the RL pipeline works correctly
models=("llama3.1_8b" "llama3.2_3b")

for attribute in "${ctg_attributes[@]}"
do
    for seed in "${seeds[@]}"
    do
        for model in "${models[@]}"
        do
            for version in "v1" "v2" "v3"
            do
                echo "Starting RL training for $model on $attribute task (seed $seed, reward $version)..."
                python scripts/rl_peft/train_rl_model.py \
                    --config_path config/rl_train_${model}_${attribute}.yaml \
                    --seed $seed \
                    --model_dir models \
                    --reward_version $version \
                    --run_name rl_${model}_${attribute}_${version}_seed${seed}
            done
        done
    done
done
