attribute: "topic"
padding: "right"
max_seq_length: 1024
control_attribute_values: ['Sports', 'Science/Technology', 'Business', 'World']

evaluation:
  metrics:
    - slor
    - accuracy
    - distinct-n
    
